# Generated by Django 6.0.3 on 2026-03-12 21:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('customers', '0001_initial'),
        ('deliveries', '0001_initial'),
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('picking', models.CharField(max_length=20)),
                ('order_number', models.CharField(max_length=30)),
                ('order_route', models.CharField(blank=True, max_length=50)),
                ('typing_date', models.DateTimeField(blank=True, null=True, verbose_name='Digitação')),
                ('release_date', models.DateTimeField(blank=True, null=True, verbose_name='Liberação')),
                ('pre_invoice_date', models.DateTimeField(blank=True, null=True, verbose_name='Pré-Nota')),
                ('invoice_number', models.CharField(blank=True, max_length=50, verbose_name='NF')),
                ('scheduled_date', models.CharField(blank=True, max_length=50, verbose_name='Data Programada')),
                ('condition', models.CharField(blank=True, max_length=100, verbose_name='Condição')),
                ('operation', models.CharField(blank=True, max_length=100, verbose_name='Operação')),
                ('origin', models.CharField(blank=True, max_length=100, verbose_name='Origem')),
                ('typist', models.CharField(blank=True, max_length=100, verbose_name='Digitador')),
                ('salesperson', models.CharField(blank=True, max_length=100, verbose_name='Vendedor')),
                ('releaser', models.CharField(blank=True, max_length=100, verbose_name='Liberador')),
                ('status', models.CharField(choices=[('pending', 'Aguardando'), ('confirmed', 'Confirmado'), ('in_progress', 'Em Progresso'), ('shipped', 'Expedido'), ('failed', 'Falha')], default='pending', max_length=20, verbose_name='Status')),
                ('situation', models.CharField(blank=True, max_length=100, verbose_name='Situação')),
                ('pending_payment', models.CharField(blank=True, max_length=100, verbose_name='Pendência')),
                ('net_weight', models.DecimalField(blank=True, decimal_places=4, max_digits=15, null=True, verbose_name='Peso Líquido')),
                ('total_volumes', models.PositiveIntegerField(blank=True, default=None, help_text='Quantidade de volumes confirmada para impressão (persiste para relatórios).', null=True, verbose_name='Total de Volumes')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customers.customer')),
                ('delivery', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='deliveries.delivery')),
            ],
            options={
                'db_table': 'orders',
                'unique_together': {('picking', 'order_number')},
            },
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=3, default=0, max_digits=18)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='orders.order')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.product')),
            ],
            options={
                'db_table': 'order_items',
                'unique_together': {('order', 'product')},
            },
        ),
    ]
