# Generated by Django 6.0.3 on 2026-03-09 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_order_situation_alter_order_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('pending', 'Aguardando'), ('confirmed', 'Confirmado'), ('in_progress', 'Em Progresso'), ('shipped', 'Expedido')], default='pending', max_length=20, verbose_name='Status'),
        ),
    ]
