site_name: Picking Ticket Printer System
site_description: Documentação técnica do sistema de orquestração de pedidos e impressão ZPL.
site_author: Equipe de Desenvolvimento

theme:
  name: material
  features:
    - navigation.tabs
    - navigation.sections
    - navigation.top
    - search.suggest
    - search.highlight
    - content.code.copy
  palette:
    - scheme: default
      primary: indigo
      accent: deep purple
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    - scheme: slate
      primary: indigo
      accent: deep purple
      toggle:
        icon: material/brightness-4
        name: Switch to light mode

plugins:
  - search

markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.tasklists:
      custom_checkbox: true

nav:
  - Início: index.md
  - Arquitetura: architecture.md
  - Componentes:
      - Apps: components/apps.md
      - Impressão (ZPL): components/printing.md
      - Celery & Redis: components/background_tasks.md
  - Guias:
      - Desenvolvimento: guides/development.md
      - Implantação: guides/deployment.md
