# Generated by Django 6.0.3 on 2026-05-01 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp_sync', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='erpsynclog',
            options={'ordering': ['-last_checked_at'], 'verbose_name': 'Log de Sincronização ERP', 'verbose_name_plural': 'Logs de Sincronização ERP'},
        ),
        migrations.AddField(
            model_name='erpsynclog',
            name='last_checked_at',
            field=models.DateTimeField(auto_now=True, help_text='Atualizado em toda requisição à API, mesmo sem novos pedidos.', verbose_name='Última Verificação'),
        ),
        migrations.AlterField(
            model_name='erpsynclog',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Primeira Sincronização'),
        ),
        migrations.AlterField(
            model_name='erpsynclog',
            name='finished_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Última Conclusão'),
        ),
        migrations.AddConstraint(
            model_name='erpsynclog',
            constraint=models.UniqueConstraint(fields=('sync_date', 'branch_ids'), name='erp_sync_log_date_branches_uniq'),
        ),
    ]
