"""
Django settings for core project.

Generated by 'django-admin startproject' using Django 6.0.3.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

import os
from datetime import timedelta
from pathlib import Path

import environ
from django.urls import reverse_lazy
from django.utils.translation import gettext_lazy as _

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

env = environ.Env(
    # set casting, default value
    DEBUG=(bool, False)
)

# Take environment variables from .env file
ENVIRONMENT = os.getenv("DJANGO_ENV", "development")

if ENVIRONMENT == "development":
    environ.Env.read_env(BASE_DIR / ".env")

SENTRY_DSN = os.getenv("SENTRY_DSN", "").strip()
if SENTRY_DSN and SENTRY_DSN.startswith(("http://", "https://")):
    import sentry_sdk
    from sentry_sdk.integrations.django import DjangoIntegration

    sentry_sdk.init(
        dsn=SENTRY_DSN,
        integrations=[DjangoIntegration()],
        environment=os.getenv("SENTRY_ENVIRONMENT", "development"),
        traces_sample_rate=1.0,
        send_default_pii=True,
    )


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.getenv("SECRET_KEY")
SIGNING_KEY = os.getenv("SIGNING_KEY")

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = env("DEBUG", default=False)

ALLOWED_HOSTS = env.list("ALLOWED_HOSTS", default=[
    "localhost",
    "127.0.0.1",
    "picking-ticket-printer-django-system-production-f15d.up.railway.app",
    "tickets.avancefarma.com.br",
    "*"
])

CSRF_TRUSTED_ORIGINS = env.list(
    "CSRF_TRUSTED_ORIGINS",
    default=[
        "http://localhost:8000",
        "http://127.0.0.1:8000",
        "https://picking-ticket-printer-django-system-production-f15d.up.railway.app",
        "https://tickets.avancefarma.com.br"
    ]
)


# Application definition

INSTALLED_APPS = [
    "unfold",
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "tailwind",
    "theme",
    "corsheaders",
    "rest_framework",
    "rest_framework_simplejwt",
    "drf_spectacular",
    "apps.core",
    "apps.authentication",
    "apps.customers",
    "apps.products",
    "apps.addresses",
    "apps.orders",
    "apps.imports",
    "apps.deliveries",
    "apps.ticket_printer",
    "apps.erp_sync",
]

MIDDLEWARE = [
    "core.middleware.HealthCheckMiddleware",
    "django.middleware.security.SecurityMiddleware",
    "whitenoise.middleware.WhiteNoiseMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "corsheaders.middleware.CorsMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]

LOGIN_URL = 'login'
LOGIN_REDIRECT_URL = '/'
LOGOUT_REDIRECT_URL = 'login'

TAILWIND_APP_NAME = "theme"
NPM_BIN_PATH = str(BASE_DIR / "wsl_npm.bat")
INTERNAL_IPS = ["127.0.0.1"]

ROOT_URLCONF = "core.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [BASE_DIR / "core" / "templates"],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "core.wsgi.application"


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

# Railway injects DATABASE_URL — use it with priority
if os.getenv("DATABASE_URL"):
    DATABASES = {"default": env.db_url("DATABASE_URL")}
elif os.getenv("POSTGRES_DB"):
    DATABASES = {
        "default": {
            "ENGINE": "django.db.backends.postgresql_psycopg2",
            "NAME": os.getenv("POSTGRES_DB"),
            "USER": os.getenv("POSTGRES_USER"),
            "PASSWORD": os.getenv("POSTGRES_PASSWORD"),
            "HOST": os.getenv(
                "POSTGRES_HOST",
                os.getenv("DB_HOST", os.getenv("PGHOST"))
            ),
            "PORT": os.getenv(
                "POSTGRES_PORT",
                os.getenv("DB_PORT", os.getenv("PGPORT", "5432"))
            ),
        }
    }
else:
    DATABASES = {
        "default": {
            "ENGINE": "django.db.backends.sqlite3",
            "NAME": str(BASE_DIR / "db.sqlite3"),
        }
    }


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation."
        "UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation."
        "MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation."
        "CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation."
        "NumericPasswordValidator",
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = "pt-br"

TIME_ZONE = "America/Sao_Paulo"

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = "static/"
STATIC_ROOT = env("STATIC_ROOT", default=BASE_DIR / "staticfiles")

# WhiteNoise: compressed and hashed static files for production
STORAGES = {
    "staticfiles": {
        "BACKEND": "whitenoise.storage.CompressedManifestStaticFilesStorage",
    },
}

# Media files
MEDIA_URL = "media/"
MEDIA_ROOT = env("MEDIA_ROOT", default=BASE_DIR / "media")

# Default primary key field type
# https://docs.djangoproject.com/en/6.0/ref/settings/#default-auto-field
DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"

# CORS
CORS_ALLOW_ALL_ORIGINS = env.bool("CORS_ALLOW_ALL_ORIGINS", default=DEBUG)

# DRF & SimpleJWT
REST_FRAMEWORK = {
    "DEFAULT_AUTHENTICATION_CLASSES": (
        "rest_framework.authentication.SessionAuthentication",
        "rest_framework_simplejwt.authentication.JWTAuthentication",
    ),
    "DEFAULT_PERMISSION_CLASSES": (
        "rest_framework.permissions.IsAuthenticated",
        "rest_framework.permissions.DjangoModelPermissions",
    ),
    "DEFAULT_THROTTLE_CLASSES": [
        "rest_framework.throttling.AnonRateThrottle",
        "rest_framework.throttling.UserRateThrottle",
    ],
    "DEFAULT_THROTTLE_RATES": {
        "anon": "100/day",
        "user": "1000/day",
        "auth": "5/min",
    },
    "DEFAULT_SCHEMA_CLASS": "drf_spectacular.openapi.AutoSchema",
}

SIMPLE_JWT = {
    "ACCESS_TOKEN_LIFETIME": timedelta(minutes=30),
    "REFRESH_TOKEN_LIFETIME": timedelta(days=7),
    "ROTATE_REFRESH_TOKENS": True,
    "BLACKLIST_AFTER_ROTATION": True,
    "UPDATE_LAST_LOGIN": False,
    "ALGORITHM": "HS256",
    "SIGNING_KEY": SIGNING_KEY or "change-me-jwt-key",
    "VERIFYING_KEY": None,
    "AUDIENCE": None,
    "ISSUER": None,
    "JSON_ENCODER": None,
    "JWK_URL": None,
    "LEEWAY": 0,
    "AUTH_HEADER_TYPES": ("Bearer",),
    "AUTH_HEADER_NAME": "HTTP_AUTHORIZATION",
    "USER_ID_FIELD": "id",
    "USER_ID_CLAIM": "user_id",
    "USER_AUTHENTICATION_RULE": (
        "rest_framework_simplejwt.authentication.default_user_authentication_rule"  # noqa: E501
    ),
    "AUTH_TOKEN_CLASSES": ("rest_framework_simplejwt.tokens.AccessToken",),
    "TOKEN_TYPE_CLAIM": "token_type",
    "TOKEN_USER_CLASS": "rest_framework_simplejwt.models.TokenUser",
    "JTI_CLAIM": "jti",
}

SPECTACULAR_SETTINGS = {
    "TITLE": "Picking Ticket Printer API",
    "DESCRIPTION": "API for Managing Logistics Orders and Label Printing",
    "VERSION": "1.0.0",
    "SERVE_INCLUDE_SCHEMA": False,
}

# Celery Configuration
# Use REDIS_URL from Railway which includes proper authentication
CELERY_BROKER_URL = os.getenv("REDIS_URL", "redis://redis:6379/0")
CELERY_RESULT_BACKEND = os.getenv("CELERY_RESULT_BACKEND", "rpc://")
CELERY_ACCEPT_CONTENT = ["json"]
CELERY_TASK_SERIALIZER = "json"
CELERY_RESULT_SERIALIZER = "json"
CELERY_TIMEZONE = TIME_ZONE

# ─── Celery Beat — Agendamento de tarefas periódicas ────────────────────────
# Intervalo configurável via variável de ambiente (padrão: 10 minutos)
_ERP_SYNC_INTERVAL_MINUTES = int(os.getenv("ERP_SYNC_INTERVAL_MINUTES", "10"))

CELERY_BEAT_SCHEDULE = {
    "sync-erp-orders-periodic": {
        "task": "erp_sync.sync_erp_orders",
        "schedule": _ERP_SYNC_INTERVAL_MINUTES * 60,  # em segundos
    },
}

# ─── Integração ERP (API Avance) ─────────────────────────────────────────────
# URL base, credenciais e filiais configuráveis via variáveis de ambiente
ERP_API_BASE_URL = os.getenv("ERP_API_BASE_URL", "http://187.117.44.93:55050")
ERP_API_USERNAME = os.getenv("ERP_API_USERNAME", "avance")
ERP_API_PASSWORD = os.getenv("ERP_API_PASSWORD", "@@polmsgtiodp%%%348*op3!!gflopat")

# IDs das filiais a sincronizar: RJ=27, ES=19
# Para alterar via env: ERP_BRANCH_IDS=27,19
_branch_ids_env = os.getenv("ERP_BRANCH_IDS", "27,19")
ERP_BRANCH_IDS = [int(b.strip()) for b in _branch_ids_env.split(",") if b.strip()]

# Intervalo em minutos (usado tanto pelo Beat quanto para referência)
ERP_SYNC_INTERVAL_MINUTES = _ERP_SYNC_INTERVAL_MINUTES

# Cache Configuration (Redis)
if os.getenv("REDIS_URL") or os.getenv("POSTGRES_DB"):
    CACHES = {
        "default": {
            "BACKEND": "django_redis.cache.RedisCache",
            "LOCATION": os.getenv("REDIS_URL", "redis://redis:6379/1"),
            "OPTIONS": {
                "CLIENT_CLASS": "django_redis.client.DefaultClient",
            },
        }
    }
else:
    CACHES = {
        "default": {
            "BACKEND": "django.core.cache.backends.locmem.LocMemCache",
        }
    }


# Session Configuration (Redis)
# Use Redis for sessions to avoid corruption issues with database sessions
SESSION_ENGINE = "django.contrib.sessions.backends.cache"
SESSION_CACHE_ALIAS = "default"
SESSION_COOKIE_AGE = 1209600  # 2 weeks
SESSION_COOKIE_HTTPONLY = True
SESSION_COOKIE_SAMESITE = "Lax"


# ─── Security Best Practices ─────────────────
X_FRAME_OPTIONS = "DENY"

# Railway (and most PaaS) terminate TLS at the proxy layer.
# This header tells Django to trust the proxy's X-Forwarded-Proto header.
SECURE_PROXY_SSL_HEADER = ("HTTP_X_FORWARDED_PROTO", "https")

if not DEBUG:
    # Default False: Railway handles TLS at the edge, so Django should not redirect.
    # Set SECURE_SSL_REDIRECT=True only if you handle TLS differently.
    SECURE_SSL_REDIRECT = env.bool("SECURE_SSL_REDIRECT", default=False)
    SESSION_COOKIE_SECURE = True
    CSRF_COOKIE_SECURE = True
    SECURE_HSTS_SECONDS = env.int("SECURE_HSTS_SECONDS", default=31536000)
    SECURE_HSTS_INCLUDE_SUBDOMAINS = True
    SECURE_HSTS_PRELOAD = True


# ─── Unfold Theme Configuration ──────────────
UNFOLD = {
    "SITE_TITLE": "Admin de Romaneios",
    "SITE_HEADER": "Sistema de Romaneios",
    "SITE_URL": "/",
    "SITE_SYMBOL": "local_shipping",  # Material symbol
    "DASHBOARD_CALLBACK": "core.admin_dashboard.dashboard_callback",
    "SIDEBAR": {
        "show_search": True,
        "show_all_applications": True,
        "navigation": [
            {
                "title": _("Painel de Controle"),
                "separator": True,
                "items": [
                    {
                        "title": _("Início"),
                        "icon": "dashboard",
                        "link": reverse_lazy("admin:index"),
                    },
                ],
            },
            {
                "title": _("Logística"),
                "separator": True,
                "items": [
                    {
                        "title": _("Pedidos"),
                        "icon": "inventory_2",
                        "link": reverse_lazy("admin:orders_order_changelist"),
                    },
                    {
                        "title": _("Itens de Pedido"),
                        "icon": "receipt_long",
                        "link": reverse_lazy(
                            "admin:orders_orderitem_changelist"
                        ),
                    },
                ],
            },
            {
                "title": _("Catálogo"),
                "separator": True,
                "items": [
                    {
                        "title": _("Produtos"),
                        "icon": "category",
                        "link": reverse_lazy(
                            "admin:products_product_changelist"
                        ),
                    },
                ],
            },
            {
                "title": _("Diretório"),
                "separator": True,
                "items": [
                    {
                        "title": _("Clientes"),
                        "icon": "people",
                        "link": reverse_lazy(
                            "admin:customers_customer_changelist"
                        ),
                    },
                    {
                        "title": _("Endereços"),
                        "icon": "location_on",
                        "link": reverse_lazy(
                            "admin:addresses_address_changelist"
                        ),
                    },
                ],
            },
            {
                "title": _("Documentação"),
                "separator": True,
                "items": [
                    {
                        "title": _("Terminal da API (Swagger)"),
                        "icon": "api",
                        "link": reverse_lazy("swagger-ui"),
                    },
                    {
                        "title": _("Docs do Sistema (MkDocs)"),
                        "icon": "menu_book",
                        "link": "/docs/",
                    },
                    {
                        "title": _("Manual de Utilização"),
                        "icon": "import_contacts",
                        "link": "/docs/manual/user_manual/",
                    },
                ],
            },
        ],
    },
}
